name: Run the load tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    run-load-test:
        runs-on: ubuntu-latest

        steps:
            - name: Check out project
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Clean install the project
              run: npm ci

            - name: Run load tests
              run: npm run test:load

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: artillery-report
                  path: tests/load/reports/
